# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: 20250821_new_boost
  name:
  - LowSupplyTemperature_rhboost
  - LowSupplyTemperature_hpboost
  - LowSupplyTemperature_noboost
  - NoPTES_LowSupplyTemperature
  - HighSupplyTemperature_rhboost
  - HighSupplyTemperature_hpboost
  - HighSupplyTemperature_noboost
  - NoPTES_HighSupplyTemperature
  - 0.75PTESCAPEX
  - 0.5PTESCAPEX
  - 0.25PTESCAPEX
  - 0PTESCAPEX
  - 1.25PTESCAPEX
  - 1.5PTESCAPEX
  - 1.75PTESCAPEX
  - 2PTESCAPEX
  scenarios:
    enable: true
    manual_file: config/scenarios.sysgf.yaml
    file: config/scenarios.automated.yaml
  shared_resources:
    policy: base #stops recalculating
    exclude:
    - existing_heating.csv   # specify files which should not be shared between scenarios
    - costs
    - retrieve_cost   # This is necessary to save retrieve_cost_data_{year}.log in the correct folder
    - industry_sector_ratios
    - build_industry_sector_ratios   # This is necessary to save build_industry_sector_ratios_data.log in the correct folder
    - modify_existing_heating

foresight: myopic

scenario:
  ll:
  - vopt
  clusters:
  - 27 #current options: 27, 49
  opts:
  - ''
  sector_opts:
  - none
  planning_horizons:
  # - 2020
  # - 2025
  # - 2030
  # - 2035
  # - 2040
  - 2045

fix_foreign_investments:
  enable: true
  reference_scenario: NoPTES_LowSupplyTemperature
  nom_min: true
  nom_max: false
  slack: 1.e-4

clustering:
  temporal:
    resolution_sector: 3H

adjustments:
  electricity: false
  sector:
    absolute:
      Store:
        urban central water pits:
          standing_loss: 0.000078
        urban central water tanks:
          standing_loss: 0.000077
wasserstoff_kernnetz:
  enable: false

sector:
  chp:
    enable: true
  district_heating:
    potential:
      DE: 0.5
      default: 0.5
    supply_temperature_approximation:
      max_forward_temperature_baseyear:
        FR: 110
        DK: 75
        DE: 124
        CZ: 130
        FI: 115
        PL: 130
        SE: 102
        IT: 90
      min_forward_temperature_baseyear:
        DE: 82
      return_temperature_baseyear:
        DE: 58
      lower_threshold_ambient_temperature: 0
      upper_threshold_ambient_temperature: 10
      rolling_window_ambient_temperature: 72
      relative_annual_temperature_reduction: 0.01
    subnodes:
      enable: true
      nlargest: 40
      census_areas:
        enable: true
        min_district_heating_share: 0.01
        processing:
          min_area: [10000, 100000, 0, 1000000]
          buffer_factor: [0.01, 0.05, 0.05, 0]
          buffer_absolute: 5
      limit_ptes_potential:
        enable: true
        limit_mother_nodes: true
        excluder_resolution: 10
        osm_landcover_codes: [21, 23, 32, 33]
        max_groundwater_depth: -10
        min_area: 25000
        default_capacity: 4500
    limited_heat_sources:
      geothermal:
        ignore_missing_regions: true
    ptes:
      enable: true
      dynamic_capacity: false
      booster_technologies: ["ptes"]
      discharger_temperature_boosting_required: true
      charger_temperature_boosting_required: false
      max_top_temperature: 90
      min_bottom_temperature: 35
      clip_network_temperature: true
    ttes:
      enable: true
    ates:
      enable: false
    dh_area_buffer: 5000
  tes: true
  tes_tau:
    decentral: 3
    central: 180
  heat_pump_sources:
    urban central:
    - air
    - geothermal
    - river_water
    - sea_water
    - ptes
    urban decentral:
    - air
    rural:
    - air
    - ground
  electrobiofuels: false

solving:
  mem_mb: 140000
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
    efuel_export_ban: false
    limits_capacity_max:
      Generator: {}
    limits_capacity_min:
      Generator: {}
  options:
    noisy_costs: true
    skip_iterations: false
    min_iterations: 1
    max_iterations: 1
  solver_options:
    gurobi-default:
      Seed: 123
      BarConvTol: 1.e-6
      FeasibilityTol: 1.e-6
      # Crossover: 1
      # NumericFocus: 3


plotting:
  dual_comparison:
    enable: true
    scenario_A: NoPTES
    scenario_B: LowSupplyTemperature_hpboost
  sensitivities:
    enable: false
    reference: LowSupplyTemperature_hpboost
    runs: [
      0PTESCAPEX, 0.25PTESCAPEX, 0.5PTESCAPEX, 0.75PTESCAPEX, 1.25PTESCAPEX, 1.5PTESCAPEX, 1.75PTESCAPEX, 2PTESCAPEX
    ]
  scenario_tuples:
    - ["NoPTES", "LowSupplyTemperature_hpboost"]
    - ["NoPTES", "LowSupplyTemperature_rhboost"]
    - ["NoPTES", "LowSupplyTemperature_noboost"]
    - ["LowSupplyTemperature_rhboost", "LowSupplyTemperature_hpboost"]
    - ["NoPTES", "HighSupplyTemperature_hpboost"]
    - ["NoPTES", "HighSupplyTemperature_rhboost"]
    - ["NoPTES", "HighSupplyTemperature_noboost"]
    - ["HighSupplyTemperature_rhboost", "HighSupplyTemperature_hpboost"]

  save_png: true
  save_pdf: true
  override_tech_colors:
    urban central water tanks charger: "#4a5cffc1"
    urban central water tanks discharger: "#4a5cffc1"
    urban central water tanks: "#4a5cffc1"
    urban central water pits charger: "#000F92C1"
    urban central water pits discharger: "#000F92C1"
    urban central water pits: "#000F92C1"
    urban central water tanks load: "#4a5cffc1"
    urban central water tanks generation: "#4a5cffc1"
    urban central water pits load: "#000F92C1"
    urban central water pits generation: "#000F92C1"
    urban central solid biomass CHP: "forestgreen"
    urban central solid biomass CHP CC: "palegreen"
    urban central lignite CHP: "grey"
    urban central coal CHP: "dimgrey"
    urban central oil CHP: "darkolivegreen"
    urban central H2 CHP: "purple"
    urban central geothermal heat direct utilisation: "olive"
    urban central geothermal heat pump: "khaki"
    urban central heat vent: "red"
    urban central resistive heater: "#28DBA6"
    urban central air heat pump: "#00FF0D"
    urban central river_water heat pump: "#FF9A03"
    urban central sea_water heat pump: "#E27C00"
    low-temperature heat for industry: "#929292"
    waste CHP: "plum"
    Fischer-Tropsch: "slateblue"
    urban central water tanks losses: "mediumspringgreen"
    urban central water pits losses: "mediumseagreen"
    other technologies: "dimgrey"
    neighbour countries: "#D0C7FF"
    CHP: "brown"
    PV: "#FFC13C"
    wind power: "skyblue"
    H2 OCGT: "#8A2BE2"
    decentral heat pump: "#556B2F"
    power grid: "#0026ffff"
    decentral biomass boiler: "#007910"
    urban central heat: "#CCCCCC"
    biomass to liquid CC: "#B0FF90"

