# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: 20250704_fix_neighbours
  name:
  - Baseline
  - LowDH
  - HighDH
  - LowPTESCAPEX
  - HighPTESCAPEX
  # - Baseline_control
  # - Baseline_fix_foreign_investments_.01slack
  # - Baseline_fix_foreign_investments_.1slack
  # - Baseline_fix_foreign_investments_1slack
  # - Baseline_fix_foreign_investments_5slack
  # - Baseline_fix_foreign_investments_10slack
  # - Baseline_fix_foreign_investments_20slack
  # - Baseline_fix_foreign_investments_90slack
  # - TES_DE_leq_0TWh
  # - PTES_DE_leq_0TWh
  # - PTES_DE_leq_3TWh
  # - PTES_DE_leq_1TWh
  # - LowPTESCAPEX
  # - HighPTESCAPEX
  # - LowStandingLosses
  # - HighStandingLosses
  # - LowGroundWaterDepth
  # - HighGroundWaterDepth
  # - LowEtPRatio
  # - HighEtPRatio
  scenarios:
    enable: true
    manual_file: config/scenarios.sysgf.yaml
    file: config/scenarios.automated.yaml
    fix_foreign_investments:
      enable: false
      nom_min: true
      nom_max: false
      reference_scenario: Baseline
      slack: 0.01
  shared_resources:
    policy: base #stops recalculating
    exclude:
    - existing_heating.csv   # specify files which should not be shared between scenarios
    - costs
    - retrieve_cost   # This is necessary to save retrieve_cost_data_{year}.log in the correct folder
    - industry_sector_ratios
    - build_industry_sector_ratios   # This is necessary to save build_industry_sector_ratios_data.log in the correct folder
    - modify_existing_heating

foresight: myopic

scenario:
  ll:
  - vopt
  clusters:
  - 27 #current options: 27, 49
  opts:
  - ''
  sector_opts:
  - none
  planning_horizons:
  - 2020
  # - 2025
  # - 2030
  # - 2035
  # - 2040
  - 2045

clustering:
  temporal:
    resolution_sector: 7H

adjustments:
  electricity: false
  sector:
    absolute:
      Store:
        urban central water pits:
          standing_loss: 0.000078
        urban central water tanks:
          standing_loss: 0.000077
wasserstoff_kernnetz:
  enable: false

sector:
  chp:
    enable: true
  district_heating:
    potential: 0.5
    subnodes:
      enable: true
      nlargest: 40
    limited_heat_sources:
      geothermal:
        ignore_missing_regions: true
    ptes:
      dynamic_capacity: false
  heat_pump_sources:
    urban central:
    - air
    - geothermal
    urban decentral:
    - air
    rural:
    - air
    - ground

solving:
  mem_mb: 140000
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
    efuel_export_ban: false
    limits_capacity_max: {}
    limits_capacity_min: {}
    limits_volume_max: {}
    limits_volume_min: {}
    limits_power_max: {}
    limits_capacity_max:
      Generator: {}
    limits_capacity_min:
      Generator: {}
  options:
    noisy_costs: false
  solver_options:
    gurobi-default:
      Seed: 123
      BarConvTol: 1.e-8
      FeasibilityTol: 1.e-8
      # Crossover: 1
      # NumericFocus: 3


plotting:
  dual_comparison:
    enable: true
    scenario_A: Baseline
    scenario_B: Baseline_control
  sensitivities:
    enable: false
    reference: Baseline
    runs: [
      PTESCAPEX,
      StandingLosses,
      GroundWaterDepth,
      EtPRatio
    ]
  save_png: true
  save_pdf: true
  override_tech_colors:
    urban central water tanks charger: "cornflowerblue"
    urban central water tanks discharger: "cornflowerblue"
    urban central water tanks: "cornflowerblue"
    urban central water pits charger: "blue"
    urban central water pits discharger: "blue"
    urban central water pits: "blue"
    urban central water tanks load: "cornflowerblue"
    urban central water tanks generation: "cornflowerblue"
    urban central water pits load: "blue"
    urban central water pits generation: "blue"
    urban central solid biomass CHP: "forestgreen"
    urban central solid biomass CHP CC: "palegreen"
    urban central lignite CHP: "grey"
    urban central coal CHP: "dimgrey"
    urban central oil CHP: "darkolivegreen"
    urban central H2 CHP: "purple"
    urban central geothermal heat direct utilisation: "olive"
    urban central geothermal heat pump: "khaki"
    urban central heat vent: "red"
    urban central resistive heater: "mediumaquamarine"
    urban central air heat pump: "gold"
    low-temperature heat for industry: "darkgrey"
    waste CHP: "plum"
    Fischer-Tropsch: "slateblue"
    urban central water tanks losses: "mediumspringgreen"
    urban central water pits losses: "mediumseagreen"
    other technologies: "dimgrey"
    neighbour countries: "#D3D3D3"
    CHP: "brown"
    PV: "yellow"
    wind power: "skyblue"
    H2 OCGT: "#8A2BE2"
    decentral heat pump: "#556B2F"
    power grid: "navy"

