# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  prefix: 20250725_boosting_fixed
  name:
  - Baseline
  - Baseline_noboosting
  - Baseline_notesboosting
  - Baseline_nogridboosting
  - NoPTES
  - LowSupplyTemperature
  - HighSupplyTemperature
  - LowDH
  - HighDH
  - NoPTES_LowDH
  - NoPTES_HighDH
  - NoPTES_LowSupplyTemperature
  - NoPTES_HighSupplyTemperature
  - 0.25PTESCAPEX
  - 0.5PTESCAPEX
  - 1.25PTESCAPEX
  - 1.5PTESCAPEX
  # - LowPTESCAPEX
  # - HighPTESCAPEX
  # - LowStandingLosses
  # - HighStandingLosses
  # - LowGroundWaterDepth
  # - HighGroundWaterDepth
  # - LowEtPRatio
  # - HighEtPRatio
  scenarios:
    enable: true
    manual_file: config/scenarios.sysgf.yaml
    file: config/scenarios.automated.yaml
  shared_resources:
    policy: base #stops recalculating
    exclude:
    - existing_heating.csv   # specify files which should not be shared between scenarios
    - costs
    - retrieve_cost   # This is necessary to save retrieve_cost_data_{year}.log in the correct folder
    - industry_sector_ratios
    - build_industry_sector_ratios   # This is necessary to save build_industry_sector_ratios_data.log in the correct folder
    - modify_existing_heating

foresight: myopic

scenario:
  ll:
  - vopt
  clusters:
  - 27 #current options: 27, 49
  opts:
  - ''
  sector_opts:
  - none
  planning_horizons:
  # - 2020
  # - 2025
  # - 2030
  # - 2035
  # - 2040
  - 2045

fix_foreign_investments:
  enable: true
  reference_scenario: NoPTES
  nom_min: true
  nom_max: true
  slack: 1.e-5

clustering:
  temporal:
    resolution_sector: 9H

adjustments:
  electricity: false
  sector:
    absolute:
      Store:
        urban central water pits:
          standing_loss: 0.000078
        urban central water tanks:
          standing_loss: 0.000077
wasserstoff_kernnetz:
  enable: false

sector:
  chp:
    enable: true
  district_heating:
    potential:
      DE: 0.5
      default: 0.5
    supply_temperature_approximation:
      max_forward_temperature_baseyear:
        FR: 110
        DK: 75
        DE: 109
        CZ: 130
        FI: 115
        PL: 130
        SE: 102
        IT: 90
      min_forward_temperature_baseyear:
        DE: 82
      return_temperature_baseyear:
        DE: 58
      lower_threshold_ambient_temperature: 0
      upper_threshold_ambient_temperature: 10
      rolling_window_ambient_temperature: 72
      relative_annual_temperature_reduction: 0.01
    subnodes:
      enable: true
      nlargest: 40
    limited_heat_sources:
      geothermal:
        ignore_missing_regions: true
    ptes:
      enable: true
      dynamic_capacity: false
      booster_technologies: ["resistive heater", "air heat pump", "ptes"]
      storage_temperature_boosting: true  # discharge temperature boosting
      forward_temperature_boosting: true # charging temperature boosting
      max_top_temperature: 90
      min_bottom_temperature: 35
    ttes:
      enable: true
    ates:
      enable: false
    tes: true
    tes_tau:
      decentral: 3
      central: 180
    dh_area_buffer: 1000
  heat_pump_sources:
    urban central:
    - air
    - geothermal
    - river_water
    - sea_water
    - ptes
    urban decentral:
    - air
    rural:
    - air
    - ground
  electrobiofuels: false

solving:
  mem_mb: 140000
  constraints:
    CCL: false
    EQ: false
    BAU: false
    SAFE: false
    efuel_export_ban: false
    limits_capacity_max:
      Generator: {}
    limits_capacity_min:
      Generator: {}
  options:
    noisy_costs: true
    skip_iterations: false
    min_iterations: 1
    max_iterations: 1
  solver_options:
    gurobi-default:
      Seed: 123
      BarConvTol: 1.e-6
      FeasibilityTol: 1.e-6
      # Crossover: 1
      # NumericFocus: 3


plotting:
  dual_comparison:
    enable: true
    scenario_A: Baseline
    scenario_B: Baseline_control
  sensitivities:
    enable: false
    reference: Baseline
    runs: [
      PTESCAPEX,
      StandingLosses,
      GroundWaterDepth,
      EtPRatio
    ]
  save_png: true
  save_pdf: true
  override_tech_colors:
    urban central water tanks charger: "cornflowerblue"
    urban central water tanks discharger: "cornflowerblue"
    urban central water tanks: "cornflowerblue"
    urban central water pits charger: "blue"
    urban central water pits discharger: "blue"
    urban central water pits: "blue"
    urban central water tanks load: "cornflowerblue"
    urban central water tanks generation: "cornflowerblue"
    urban central water pits load: "blue"
    urban central water pits generation: "blue"
    urban central solid biomass CHP: "forestgreen"
    urban central solid biomass CHP CC: "palegreen"
    urban central lignite CHP: "grey"
    urban central coal CHP: "dimgrey"
    urban central oil CHP: "darkolivegreen"
    urban central H2 CHP: "purple"
    urban central geothermal heat direct utilisation: "olive"
    urban central geothermal heat pump: "khaki"
    urban central heat vent: "red"
    urban central resistive heater: "mediumaquamarine"
    urban central air heat pump: "gold"
    low-temperature heat for industry: "darkgrey"
    waste CHP: "plum"
    Fischer-Tropsch: "slateblue"
    urban central water tanks losses: "mediumspringgreen"
    urban central water pits losses: "mediumseagreen"
    other technologies: "dimgrey"
    neighbour countries: "#D3D3D3"
    CHP: "brown"
    PV: "yellow"
    wind power: "skyblue"
    H2 OCGT: "#8A2BE2"
    decentral heat pump: "#556B2F"
    power grid: "navy"

