# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

NoPTES_LowSupplyTemperature:
  adjustments:
    electricity: false
    sector:
      absolute:
        Store:
          urban central water pits:
            e_nom_max: 0

LowSupplyTemperature_hpboost:

LowSupplyTemperature_rhboost:
  sector:
    district_heating:
      ptes:
        boosting_technologies: ["resistive heater"]

LowSupplyTemperature_noboost:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  sector:
    district_heating:
      ptes:
        discharger_temperature_boosting_required: false

# Same for HighSupplyTemperature scenarios
NoPTES_HighSupplyTemperature:
  sector:
    district_heating:
      supply_temperature_approximation:
        relative_annual_temperature_reduction: 0.0
  adjustments:
    electricity: false
    sector:
      absolute:
        Store:
          urban central water pits:
            e_nom_max: 0

HighSupplyTemperature_hpboost:
  fix_foreign_investments:
    reference_scenario: NoPTES_HighSupplyTemperature

HighSupplyTemperature_rhboost:
  fix_foreign_investments:
    reference_scenario: NoPTES_HighSupplyTemperature
  sector:
    district_heating:
      ptes:
        boosting_technologies: ["resistive heater"]

HighSupplyTemperature_noboost:
  fix_foreign_investments:
    reference_scenario: NoPTES_HighSupplyTemperature
  sector:
    district_heating:
      ptes:
        discharger_temperature_boosting_required: false


0.75PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 0.75

0.5PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 0.5

0.25PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 0.25

0PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 0

1.25PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 1.25

1.5PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 1.5

1.75PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 1.75

2PTESCAPEX:
  fix_foreign_investments:
    reference_scenario: NoPTES_LowSupplyTemperature
  adjustments:
    electricity: false
    sector:
      factor:
        Store:
          urban central water pits:
            capital_cost: 2
